#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

${OPENSHIFT_DATA_DIR}set_env.sh

cd ${OPENSHIFT_REPO_DIR}stormcrew/
echo "Executing 'python ${OPENSHIFT_REPO_DIR}stormcrew/manage.py syncdb --noinput'"
$OPENSHIFT_REPO_DIR/../bin/python ${OPENSHIFT_REPO_DIR}stormcrew/manage.py syncdb --noinput

echo "Executing 'python ${OPENSHIFT_REPO_DIR}stormcrew/manage.py migrate'"
$OPENSHIFT_REPO_DIR/../bin/python ${OPENSHIFT_REPO_DIR}stormcrew/manage.py migrate

echo "Executing 'python ${OPENSHIFT_REPO_DIR}stormcrew/manage.py collectstatic --clear --noinput'"
$OPENSHIFT_REPO_DIR/../bin/python ${OPENSHIFT_REPO_DIR}stormcrew/manage.py collectstatic --clear --noinput

