#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

${OPENSHIFT_DATA_DIR}set_env.sh

cd ${OPENSHIFT_REPO_DIR}stormcrew/
$OPENSHIFT_REPO_DIR/../bin/uwsgi -s $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT --socket-protocol http --module config.wsgi:application --pp $OPENSHIFT_REPO_DIR -d $OPENSHIFT_DIY_LOG_DIR/app.log --pidfile $OPENSHIFT_TMP_DIR/uwsgi.pid

# export PATH=$OPENSHIFT_REPO_DIR/../bin:$PATH
# cat $OPENSHIFT_DIY_LOG_DIR/app.log
