#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

echo "Setting environment variables"
export DATABASE_URL=postgresql://${OPENSHIFT_POSTGRESQL_DB_USERNAME}:${OPENSHIFT_POSTGRESQL_DB_PASSWORD}@${OPENSHIFT_POSTGRESQL_DB_HOST}:${OPENSHIFT_POSTGRESQL_DB_PORT}/${OPENSHIFT_APP_NAME}
export DEBUG_DJANGO=True
export FACEBOOK_APP_ID=320855637976774
export FACEBOOK_API_SECRET=6d86ce4fea96b6d35555570eb4359829

cd $OPENSHIFT_REPO_DIR
$OPENSHIFT_REPO_DIR/../bin/uwsgi -s $OPENSHIFT_DIY_IP:$OPENSHIFT_DIY_PORT --socket-protocol http --module stormcrew.config.wsgi:application --pp $OPENSHIFT_REPO_DIR -d $OPENSHIFT_DIY_LOG_DIR/app.log --pidfile $OPENSHIFT_TMP_DIR/uwsgi.pid
